enable-feature:
  shops: true
  item-displays: true
  chest-shops: true
  info-signs: true
  composite-items: false
  player-shops: true
  scrolling-transaction-signs: false
  price-history-storage: true
  transaction-signs: true
  automatic-backups: true
  per-shop-permissions: false
  price-change-notifications: true
  treat-damaged-items-as-equals-to-undamaged-ones: true
  debug-mode: false
  uuid-support: true
  time-effects: false
economy-plugin:
  use-external: true
  hook-internal-economy-into-vault: false
  starting-player-account-balance: 0.0
sql:
  use-mysql: false
  log-sql-statements: false
  mysql-connection:
    username: default_username
    port: 3306
    password: default_password
    host: localhost
    database: minecraft
language: english
intervals:
  shop-check: 6
  save: 24000
tax:
  account: hyperconomy
  purchase: 3
  initial: 100
  static: 100
  enchant: 100
  sales: 0
  dynamic:
    enable: false
    money-floor: 0
    money-cap: 1000000
    max-tax-percent: 100
shop:
  default-server-shop-account: hyperconomy
  default-server-shop-account-initial-balance: 20000000
  display-shop-exit-message: true
  max-stock-per-item-in-playershops: 100000
  max-player-shop-volume: 1000
  max-player-shops-per-player: 1
  sell-remaining-if-less-than-requested-amount: true
  server-shops-have-unlimited-money: false
  limit-info-commands-to-shops: false
  block-selling-in-creative-mode: false
  show-currency-symbol-after-price: false
  unlimited-stock-for-static-items: false
  require-chest-shops-to-be-in-shop: false
  require-transaction-signs-to-be-in-shop: false
  send-price-change-notifications-for: diamond,diamondblock,
history:
  days-to-save: 7
enchantment:
  classvalue:
    wood: .1
    leather: .1
    stone: .15
    chainmail: .2
    iron: .25
    gold: .1
    diamond: 1
    bow: .25
    book: 1
bank:
  max-ownerships-per-player: 3
multi-server:
  enable: false
  remote-server-ip-addresses: 192.168.1.1,3313;192.168.1.1,3314;192.168.1.2,3313;
  port: 3313
  update-interval: 500
  connection-timeout-ms: 2000
  sync-shops: true
  sync-trade-objects: true
  sync-accounts: true
remote-gui:
  enable: false
  server: false
  remote-server-ip: 192.168.1.1
  remote-server-port: 3313
  listen-port: 3313
  connection-timeout-ms: 10000
  refresh-rate-ms: 20000
  auth-key: change-me
updater:
  enabled: true
  notify-in-game: true
  notify-for:
    dev-builds: true
    beta-builds: true
    recommended-builds: true
web-page:
  enable: false
  port: 7777
  background-color: 8FA685
  font-color: F2F2F2
  border-color: "091926"
  increase-value-color: C8D9B0
  decrease-value-color: F2B2A8
  highlight-row-color: 8FA685
  header-color: "091926"
  table-data-color: 314A59
  font-size: 12
  font: verdana
  enable-web-api: false
  web-api-path: API
chest-shop:
  limit-chest-shops: true
  max-per-player: 5