enable-feature:
  shops: true
  item-displays: true
  chest-shops: true
  info-signs: true
  composite-items: false
  player-shops: true
  scrolling-transaction-signs: false
  price-history-storage: true
  transaction-signs: true
  automatic-backups: true
  per-shop-permissions: false
  price-change-notifications: true
  treat-damaged-items-as-equals-to-undamaged-ones: true
  debug-mode: false
  uuid-support: true
economy-plugin:
  use-external: true
  hook-internal-economy-into-vault: false
  starting-player-account-balance: 0.0
sql:
  use-mysql: false
  log-sql-statements: false
  mysql-connection:
    username: default_username
    port: 3306
    password: default_password
    host: localhost
    database: minecraft
language: english
intervals:
  shop-check: 6
  save: 24000
tax:
  purchase: 3
  initial: 100
  static: 100
  enchant: 100
  sales: 0
  dynamic:
    enable: false
    money-floor: 0
    money-cap: 1000000
    max-tax-percent: 100
shop:
  default-server-shop-account: hyperconomy
  default-server-shop-account-initial-balance: 20000000
  display-shop-exit-message: true
  max-stock-per-item-in-playershops: 100000
  max-player-shop-volume: 1000
  max-player-shops-per-player: 1
  sell-remaining-if-less-than-requested-amount: true
  server-shops-have-unlimited-money: false
  limit-info-commands-to-shops: false
  block-selling-in-creative-mode: false
  show-currency-symbol-after-price: false
  unlimited-stock-for-static-items: false
  require-chest-shops-to-be-in-shop: false
  require-transaction-signs-to-be-in-shop: false
  send-price-change-notifications-for: diamond,diamondblock,
history:
  days-to-save: 7
enchantment:
  classvalue:
    wood: .1
    leather: .1
    stone: .15
    chainmail: .2
    iron: .25
    gold: .1
    diamond: 1
    bow: .25
    book: 1
bank:
  max-ownerships-per-player: 3