version: 0.953
config:
  shopcheckinterval: 6
  logwriteinterval: 4
  saveinterval: 6000
  signupdateinterval: 5
  purchasetaxpercent: 3
  initialpurchasetaxpercent: 100
  statictaxpercent: 300
  enchanttaxpercent: 100
  daystosavehistory: 30
  initialshopbalance: 20000000
  shop-has-unlimited-money: false
  global-shop-account: hyperconomy
  use-shop-exit-message: true
  use-notifications: true
  use-info-signs: true
  use-transaction-signs: true
  store-price-history: false
  use-chest-shops: true
  use-item-displays: true
  use-shop-permissions: false
  require-chest-shops-to-be-in-shop: false
  require-transaction-signs-to-be-in-shop: false
  currency-symbol: $
  notify-for: diamond,diamondblock,
  sales-tax-percent: 0
  run-automatic-backups: true
  unlimited-stock-for-static-items: false
  error-count: 0
  language: english
  log-errors: false
  log-sqlwrite-errors: false
  dynamic-tax:
    use-dynamic-tax: false
    money-floor: 0
    money-cap: 1000000
    max-tax-percent: 100
  enchantment:
    classvalue:
      wood: .1
      leather: .1
      stone: .15
      chainmail: .2
      iron: .25
      gold: .1
      diamond: 1
      bow: .25
  sql-connection:
    use-sql: false
    username: default
    port: 3306
    password: default
    host: localhost
    database: minecraft
    max-sql-threads: 20
  web-page:
    port: 8765
    use-web-page: true
    web-page-economy: default
    background-color: EEEEF6
    font-color: 333333
    border-color: D8DFE4
    increase-value-color: A0FFB0
    decrease-value-color: FFA0A0
    highlight-row-color: B4FAF9
    header-color: B8B4FF